//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMangerAppReviso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class working_hours
    {
        public int id { get; set; }
        public int pId { get; set; }
        public Nullable<System.DateTime> startDT { get; set; }
        public Nullable<System.DateTime> endDT { get; set; }
    
        public virtual active_projects active_projects { get; set; }
    }
}
